### ISSUE TITLE
Is there some documentation somewhere about setting up the networking for LXD

### ISSUE THREAD

**Issue by bmullan** [OpenNebula/minione#18]
I had no problem installing MiniONE,  running the default CentOS image was easy and updating it was no problem because it apparently already had its networking configured with a gateway through the host to the Internet and therefore to the CentOS repositories.

However, although I was able to download & install an Ubuntu 18.04 image/VM... once installed I found that I could not do:

sudo apt update

As there was no path to the Internet & thus to the Ubuntu repositories.

I then started trying to figure out exactly what I needed to configure do this.   I soon realized that I wasn't having much luck.

So I am opening this "issue" to ask how its done for the images that come from the default LXD Image server?

Thanks
Brian

**Comment by xorel** [comment]
You only need to add a virtual network `vnet` to the Ubuntu `VM Template`.  Compare templates `Centos 7 - KVM` and the `Ubuntu 18.04 - KVM` (or similar)  you downloaded.
