### ISSUE TITLE
Are their any complete tutorial's for Operations?   I see many fragmented or non-english ones.

### ISSUE THREAD

**Issue by bmullan** [OpenNebula/minione#19]
Once MiniONE is installed its really tough trying to figure out how to do alot of things. 

Documentation is terse & at times complex and without many examples.

Many of the Video's that exist (youtube or otherwise) are either fragments (ie covering 1 topic) or non-english.

_Is there any beginning-to-end operations video_ covering what you do after logging into MiniONE:

- how to start a VM with an Image from the LXD Image repository or linuxcontainers.org
- how to configure that VM's template so a VM started with that "image" has internet connectivity which allows it to have its package updated/upgraded or new packages added
- how to create/modify storage and assign that storage to a VM or Template
- etc

Thanks
Brian

**Comment by xorel** [comment]
There is just an overview of OpenNebula in MiniONE [read me](https://github.com/OpenNebula/minione/blob/master/README.md#try-out).

Please refer to [OpenNebula docs](http://docs.opennebula.org/5.8/) for the details.
There is also  [OpenNebula youtube channel](https://www.youtube.com/user/OpenNebula).

**Comment by bmullan** [comment]
@xorel 

I have looked at the OpenNebula in MiniONE page and its a beginning but there is a lot it leaves out such as examples of steps needed to actually configure & launch a VM ?

As to just saying...

> Please refer to OpenNebula docs for the details.
> There is also OpenNebula youtube channel.

_**Really ??**_   
**_Have you looked at the Youtube Channel through the eyes of a prospective "new" OpenNebula User/Adopter ??_**.   Just trying to be helpful here...

https://www.youtube.com/channel/UCBwSqQJQ520NYoy2QlcYJKA

_Most of those video's are about past OpenNebula Conferences?_   There are few actual tutorials for newcomers !

**_Newcomer's don't need to become discouraged_** because they can't _"find"_ out how to do something.  At least that's my experience from a lifetime in technology including 20 years at Cisco Systems where I lead Cisco's worldwide broadband consulting group.   We always documented a "Introduction to Technology X" for Newcomers as well as the normal in-depth technical Documentation.

Most Newcomer's need early "successes" with OpenNebula to capture their interest in learning more.
