### ISSUE TITLE
MiniONE does not auto-restart after its Server/Host/VM is shutdown/restarted

### ISSUE THREAD

**Issue by bmullan** [OpenNebula/minione#20]
This may be the same problem as Issue #9 but that's been open since March and doesn't appear to have been fixed/closed.

I am using MiniONE okay but the problem is that MiniONE does not auto-restart when the Server/VM/Host it is running on is shutdown or restarted?

If I shutdown the VM/HOST and later restart it... how do I restart MiniONE so I don't have to just reinstall it and start all my work over again?

thanks
Brian

**Comment by xorel** [comment]
Duplicate #9.

You need to start `opennebula` and `opennebula-sunstone` services after the reboot (or enable them).

VMs on the rebooted host could be resumed with the `onevm resume [$VM_ID]` command or using the web ui.

**Comment by bmullan** [comment]
Joel
Thanks for your response

> You need to start opennebula and opennebula-sunstone services after the reboot (or enable them).

But you be more explicit?  Remembering I (or many others) may be new to OpenNebula and unfamiliar with what commands to use?

Is there a section of the Documentation that describes this that you can point to.?

**Comment by dkorzhevin** [comment]
@bmullan seems like autostart issue was due opennebula services was not enabled by install script.

This was fixed: https://github.com/OpenNebula/minione/commit/cf2fd2d1337e3b23aa4bad1c9625b01bd222a7b7

**Comment by bmullan** [comment]
Thanks
