### ISSUE TITLE
short video to demo installing and using miniONE w LXD Hypervisor

### ISSUE THREAD

**Issue by bmullan** [OpenNebula/minione#21]
Don't know if this is of value but I made a short video to demo how I installed & configured miniONE with LXD as the Hypervisor then create two LXD OpenNebula "VMs".

https://drive.google.com/file/d/1RGtCd2E7XmUSK1tWIkDa1IA4E6YBa0RM/view

I also posted this video on the LXD sub-reddit:

https://www.reddit.com/r/LXD/comments/bnqhx1/opennebula_cloud_orchestration_with_lxd_using/

and  on the LXD User Forum in order to help others get started...

https://discuss.linuxcontainers.org/t/opennebula-cloud-orchestration-with-lxd-using-opennebulas-minione-one-being-opennebulas-acronym-for-opennebula-installs-in-just-a-few-minutes/4768/11

I also put it on youtube but image quality doesn't seem as good there for some reason.

Brian

**Comment by xorel** [comment]
Thanks, Brian we appreciate it!

Perhaps better channel might be the [forum](https://forum.opennebula.org/) where other users could benefit from that information.
