### ISSUE TITLE
Please add to the section "Quick Overview of the CLI Interface" how to restart OpenNebula and SunStone

### ISSUE THREAD

**Issue by bmullan** [OpenNebula/minione#22]
MiniONE **_does not restart automatically_** upon shutdown/reboot of its Host (host server or VM).

I was told that the way to do this manually was:

> enable like any other service using systemctl enable opennebula opennebula-sunstone

This should really be added to the README.md file's section "**_Quick Overview of the CLI Interface_**"!

**Comment by vholer** [comment]
Latest release already enables the services on boot properly.

Also, there is a new tutorial which covers the service management commands:
https://github.com/OpenNebula/minione/wiki/Troubleshooting

Closing.
