### ISSUE TITLE
Have the limitations of LXD changed since the Web Page was published?

### ISSUE THREAD

**Issue by bmullan** [OpenNebula/minione#26]
http://docs.opennebula.org/5.8/deployment/open_cloud_host_setup/lxd_driver.html#requirements
For the LXD Driver the above page lists the following "Considerations & Limitations Host issues"

There are a number of regular features that are not implemented yet:

- snapshots
- live migration
- save/restore
- live disk resize
- LVM datastore
- PCI Passthrough
- volatile filesystems
- offline disk resize:
- not supported on multiple partition images
-        only supported xfs and ext4 filesystems

**Comment by dann1** [comment]
Hi @bmullan, [there is a WIP](https://github.com/OpenNebula/one/pull/3344) regarding volatile fs, but for the rest of those features, we just have some open issues users could upvote.

For questions/doubts, I think it would be better to ask them in the forum, that way you could receive more feedback from our community.

**Comment by bmullan** [comment]
@dann1 

> Hi @bmullan, [there is a WIP](https://github.com/OpenNebula/one/pull/3344) regarding volatile fs, but for the rest of those features, we just have some open issues users could upvote.
> 
> For questions/doubts, I think it would be better to ask them in the forum, that way you could receive more feedback from our community.

_How does a user "upvote" an issue ?_

**Comment by dann1** [comment]
Give the thumbups on the first issue comment, in the reaction menu.

![image](https://user-images.githubusercontent.com/16429804/58809219-22d48680-85e1-11e9-97e8-df9e19cde5e5.png)
