### ISSUE TITLE
minione environment preparation failure due to unfinished install

### ISSUE THREAD

**Issue by dkorzhevin** [OpenNebula/minione#27]
minione failed to prepare environment because somehow it not able to install all packages, which led to error loop.

1. Fail on package get/installation:

```
Installing OpenNebula node packages  FAILED
apt-get install -y opennebula-node
--- STDERR ---
E: Failed to fetch http://mirror.leaseweb.com/ubuntu/pool/main/u/usbredir/libusbredirparser1_0.7.1-1_amd64.deb  Undetermined Error [IP: 37.58.58.140 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
--------------
```

2. Failure to continue install due to existing partial install:

```
# ./minione

### Checks & detection
Checking directories from previous installation  FAILED
```

3. Option force (-f) didn't helped because existing route exist:

```
# ./minione -f

### Checks & detection
Checking directories from previous installation  IGNORED will be deleted
Checking user from previous installation  IGNORED will be deleted
Checking minionebr interface is not present  IGNORED
Checking virtual network 172.16.100.0/24 is not routed  FAILED
```

4. Installation continued only when existing route was deleted (blocker):

```
ip route del 172.16.100.0/24
```

It would be good to at least clarify error messages a bit (for example, additionally notify about force option (-f) and route remove.

**Comment by xorel** [comment]
We will add some retries to prevent failing installation (#23).

Anyway, before running the `minione` again it's always better to run `./minione --purge` first.

**Comment by dkorzhevin** [comment]
Thank you
