### ISSUE TITLE
Add NTP server to MiniONE

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/minione#31]
---

Author Name: **Ruben S. Montero** (@rsmontero)
Original Redmine Issue: 4719, https://dev.opennebula.org/issues/4719
Original Date: 2016-08-17

---

As pointed out here:

https://forum.opennebula.org/t/connecting-sandbox-to-azure-for-cloud-burstin-fails/2739/3

**Comment by xorel** [comment]
I don't think this should be part of the minione.
