### ISSUE TITLE
Wait until Marketplace image is imported

### ISSUE THREAD

**Issue by vholer** [OpenNebula/minione#36]
It happens, that the testing starts while image is still being imported as we don't wait until the image is ready in the OpenNebula:

https://github.com/OpenNebula/minione/blob/a2563ad3e1d2f46c767003e1b214347fffae8105/minione#L1147-L1153

**Comment by xorel** [comment]
When running the import in the background minione could be already done and user can look around check sunstone etc. Waiting for the image to be ready would extend the installation time quite a lot, which I don't think is necessary.
