### ISSUE TITLE
Installation fails - MTU

### ISSUE THREAD

**Issue by tobias992** [OpenNebula/minione#37]
Hello,

there is an option to set manual the MTU on installation because my installation fails. The reason is the wrong MTU when minione create the Network.

Like:
sudo bash minione --lxd --mtu=1400

**Comment by vholer** [comment]
Hello @tobias992 , can you please be more specific how custom MTU improves your situation? I don't get that's the problem with non-specified default MTU. Thank you, Vlastimil

**Comment by tobias992** [comment]
My provider has a MTU from 1400. When i install LXD normal from snap, after install i have to set the correct MTU. If i dont set them i only get network errors. (default MTU is 1500 - i need 1400)

Maybe this is the reason why the installation with minione script fails.
