### ISSUE TITLE
"CentOS7 5.8" not in Ubuntu18.04 5.8

### ISSUE THREAD

**Issue by bvbek** [OpenNebula/minione#40]
I try to install minione/openNebula  inside LXD/LXC container.
Host system Ubuntu 18.04
Lxd/Lxc container centos 7
      bash minione --lxd --force
error:
--- STDERR ---
"CentOS7 5.8" not in Ubuntu18.04 5.8

Do is any way to install OpenNebula/minione inside any HOST->container?

**Comment by xorel** [comment]
Minione only supports LXD installation on Ubuntu 18.04 not on CentOS. Whether it works within the container I don't know.
