### ISSUE TITLE
OneGate not reachable for edge cloud VMs

### ISSUE THREAD

**Issue by vholer** [OpenNebula/minione#41]
In the `oned.conf`, OneGate endpoint is configured for local VMs. But, this is the private IP address unreachable for remote edge cloud VMs. E.g.,

```
ONEGATE_ENDPOINT = "http://172.16.100.1:5030"
```

Maybe we can have OneGate to listen on all interfaces (`0.0.0.0`) and simply use a primary host IP address of as universal endpoint. Not sure if it would work for both local and edge cloud VMs, hopefully yes.

**Comment by xorel** [comment]
for the frontend only (intended for oneprovision) there is
```
# FRONTEND + PREPARE FIREEDGE, ONEPROVISION
else
    ONEGATE_ENDPOINT=${PUBLIC_IP:-$ETH0_IP}                                                                                                                                  
    ONEGATE_SERVER=$ETH0_IP
    FIREEDGE_ENDPOINT=${PUBLIC_IP:-$ETH0_IP}
    REPORT_IP=${PUBLIC_IP:-$ETH0_IP}
fi
```
