### ISSUE TITLE
5.10/Ubuntu/20.04 stable Release' does not have a Release file.

### ISSUE THREAD

**Issue by Manishfoodtechs** [OpenNebula/minione#52]
I stuck here . I was installing openenbula through minione on ubuntu 20.04 

### Installation
Updating APT cache  OK
Install  augeas-tools bridge-utils apt-transport-https iptables-persistent netfilter-persistent  OK
Download augeas lens oned.aug  OK
Creating bridge interface minionebr  OK
Bring bridge interfaces up  OK
Enabling IPv4 forward  OK
Configuring NAT using iptables  OK
Saving iptables changes  OK
Installing DNSMasq  OK
Starting DNSMasq  OK
Configuring repositories  OK
Updating APT cache  FAILED

--- STDERR ---
**E: The repository 'https://downloads.opennebula.org/repo/5.10/Ubuntu/20.04 stable Release' does not have a Release file.**
--------------

**Comment by vholer** [comment]
You used `--force` to skip the failing OS / version check. Ubuntu 20.04 is not supported yet by OpenNebula. Please follow the requirements https://github.com/OpenNebula/minione#requirements .
