### ISSUE TITLE
Ubuntu 19.10 support

### ISSUE THREAD

**Issue by JuniorJPDJ** [OpenNebula/minione#53]
It's not supported, but latest OpenNebula supports this release

**Comment by bmullan** [comment]
But 19.10 is end of life in less that 3 months? (Jul 2020)

**Comment by JuniorJPDJ** [comment]
But it's latest supported version by nebula

**Comment by mala-git** [comment]
Does that mean Ubuntu 20.04 won't be supported anymore?
