### ISSUE TITLE
Reconfiguration without a previous `minione --purge`

### ISSUE THREAD

**Issue by ospalax** [OpenNebula/minione#55]
When minione installs OpenNebula it may lure someone into thinking to `reconfigure` the installation with few changed arguments from the previous run.

Minione with `--force` will try to comply but fails during the process.

Either forbid this even with `--force` argument or support proper reconfiguration (for example: new oneadmin's password, sunstone port etc.).

Examples:
```
$ bash minione --yes --lxd --frontend --version 5.11 --password badpass --sunstone-port 9869 # This runs OK
$ bash minione --yes --lxd --frontend --version 5.11 --password badpass123 --sunstone-port 80 --force # This does not do what was expected
…
Setting initial password for current user and oneadmin  FAILED

--- STDERR ---
minione: line 1254: /var/lib/one/.one/one_auth: No such file or directory
--------------
```

**Comment by xorel** [comment]
Reconfigure option would increase the complexity, perhaps, beyond the limits of evaluation tool written in bash.
