### ISSUE TITLE
Step iptables failed on "Cannot assign requested address"

### ISSUE THREAD

**Issue by vholer** [OpenNebula/minione#6]
(user report got via e-mail)

Executing the minione bash under ubuntu 18.04, I've the following answer : 

### Installation
Updating apt cache  OK
Install bridge-utils  OK
Creating bridge interface minionebr  OK
Restarting network  OK
Enabling ipv4 forward  OK
Configuring nat using iptables  FAILED
STDERR:
bind: Cannot assign requested address

**Comment by vholer** [comment]
+ reply to the user directly after fixing

**Comment by pan87232494** [comment]
+1, meet same problem, how to fix it?

**Comment by xorel** [comment]
@pan87232494 on ubuntu 18.04 or different OS?
