### ISSUE TITLE
Minione purge being incomplete on Ubuntu 20.04

### ISSUE THREAD

**Issue by megastallman** [OpenNebula/minione#69]
Running Minione script on Xubuntu 20.04, singlehost configuration.
After running "sudo bash minione --purge" all Opennebula packages stay installed. Especially the one that creates "oneadmin" user. So, there is no straightforward chance to install it again.
Also, I think that we could also delete the /var/log/one directory after Opennebula deinstallation.
So please add those last steps to --purge procedure:
```
apt -yy purge opennebula-*
rm -rf /var/log/one
```

**Comment by xorel** [comment]
Should be fixed in master, please reopen if you encounter the problem again.
