### ISSUE TITLE
<LIMIT_MB>50000</LIMIT_MB> breaks installation process and Opennebula itself

### ISSUE THREAD

**Issue by megastallman** [OpenNebula/minione#70]
Running Opennebula on Xubuntu 20.04.

I don't understand where this LIMIT_MB=50000 value comes from at all. First - it breaks Minione installer on Marketplace image download stage. Ok, after commenting that out and installing Opennebula I'm trying to add a VM image manually, but then it says that we have "no free space on datastore", while I have 100GB of 190GB free. Only when I remove that parameter from all datastores, everything works fine.
Please don't add that limit for at least, my Ubuntu 20.04 bare metal target.

**Comment by xorel** [comment]
Thanks for reporting.
I removed the datastore limit, seems it only served as a workaround for a faster datastore monitor after the DS update.
