### ISSUE TITLE
Report not shown

### ISSUE THREAD

**Issue by Andrysky** [OpenNebula/minione#72]
ubuntu 20.10
```
wget 'https://github.com/OpenNebula/minione/releases/latest/download/minione'
chmod +x  ./minione 
sudo bash minione -f
```
in 
[https://docs.opennebula.io/6.0/quick_start/deployment_basics/try_opennebula_on_kvm.html](https://docs.opennebula.io/6.0/quick_start/deployment_basics/try_opennebula_on_kvm.html)
written 

> the end of a successful deployment the miniONE tool provides a report 
> ### Report
> OpenNebula 6.0 was installed
> Sunstone is running on:
>   http://3.121.76.103/
> FireEdge is running on:
>   http://3.121.76.103:2616/
> Use following to login:
>   user: oneadmin
>   password: lCmPUb5Gwk"

**Comment by xorel** [comment]
I fixed minor bug (in the master), however minione worked on my Ubuntu 20.10.
Can you eventually share the stdout/err if some?

**Comment by Andrysky** [comment]
yes in the new version everything works))
