### ISSUE TITLE
OpenNebula services don't start after reboot

### ISSUE THREAD

**Issue by xorel** [OpenNebula/minione#9]

**Comment by bmullan** [comment]
I've got the same issue with MiniONE.   
If I shutdown the VM its installed on or reboot it ... MiniONE doesn't not automatically restart.
How or what can we do to configure MiniONE to restart when the VM/Server restarts?

thanks

**Comment by xorel** [comment]
Should be fixed in the master branch. But you can enable like any other service using `systemctl enable opennebula opennebula-sunstone`

**Comment by bmullan** [comment]
@xorel 

That's awesome Jan!   

> Should be fixed in the master branch. But you can enable like any other service using systemctl enable opennebula opennebula-sunstone

**_That is information is missing from the [MiniONE Github README page](https://github.com/OpenNebula/minione/blob/master/README.md#try-out) and needs to be added !_**
